
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqkdadugmkwnthkfjbla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxa2RhZHVnbWt3bnRoa2ZqYmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNDQwOTUsImV4cCI6MjA2MTcyMDA5NX0.AyZpQgkaypIz2thFdO2K5WF7WFXog2tw-t_9RLBapY4";

// Enhanced Supabase client with security improvements
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: typeof localStorage !== 'undefined' ? localStorage : undefined,
    detectSessionInUrl: true,
    flowType: 'pkce',
    debug: false, // Disabled debug logging for production security
  },
  global: {
    headers: {
      'x-client-domain': typeof window !== 'undefined' ? window.location.hostname : 'unknown',
      'x-client-info': 'lovable-custom-domain'
    },
    fetch: (...args: [RequestInfo, RequestInit?]) => fetch(...args)
  },
  db: {
    schema: 'public'
  }
});

// Reduced logging for security - only log essential information
if (typeof window !== 'undefined' && process.env.NODE_ENV === 'development') {
  console.log("Supabase client initialized");
  
  // Setup auth change listener with minimal logging
  supabase.auth.onAuthStateChange((event, session) => {
    if (process.env.NODE_ENV === 'development') {
      console.log("Auth state changed:", event);
      console.log("Session present:", session ? "Yes" : "No");
    }
  });
}
